/**
 * Card basket — single source of truth for all tracked cards.
 * Weights live in INDEX_CONFIGS, not on individual cards.
 *
 * TCGdex ID format: {set-id}-{card-number}
 * All cards verified to have pricing data in TCGdex.
 */
export const CARDS = [
  // ─── VINTAGE — Base Set ────────────────────────────────────────────────────
  {
    id: 'base-charizard',
    name: 'Charizard Holo',
    set: 'Base Set',
    number: '4/102',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'base1-4',
  },
  {
    id: 'base-blastoise',
    name: 'Blastoise Holo',
    set: 'Base Set',
    number: '2/102',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'base1-2',
  },
  {
    id: 'base-venusaur',
    name: 'Venusaur Holo',
    set: 'Base Set',
    number: '15/102',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'base1-15',
  },
  {
    id: 'base-pikachu',
    name: 'Pikachu',
    set: 'Base Set',
    number: '58/102',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'base1-58',
  },
  {
    id: 'base-mewtwo',
    name: 'Mewtwo Holo',
    set: 'Base Set',
    number: '10/102',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'base1-10',
  },
  {
    id: 'base-raichu',
    name: 'Raichu Holo',
    set: 'Base Set',
    number: '14/102',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'base1-14',
  },
  {
    id: 'base-gyarados',
    name: 'Gyarados Holo',
    set: 'Base Set',
    number: '6/102',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'base1-6',
  },
  {
    id: 'base-alakazam',
    name: 'Alakazam Holo',
    set: 'Base Set',
    number: '1/102',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'base1-1',
  },
  {
    id: 'base-chansey',
    name: 'Chansey Holo',
    set: 'Base Set',
    number: '3/102',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'base1-3',
  },
  {
    id: 'base-ninetales',
    name: 'Ninetales Holo',
    set: 'Base Set',
    number: '12/102',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'base1-12',
  },

  // ─── VINTAGE — Jungle ──────────────────────────────────────────────────────
  {
    id: 'jungle-scyther',
    name: 'Scyther Holo',
    set: 'Jungle',
    number: '10/64',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'base2-10',
  },
  {
    id: 'jungle-snorlax',
    name: 'Snorlax Holo',
    set: 'Jungle',
    number: '11/64',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'base2-11',
  },
  {
    id: 'jungle-jolteon',
    name: 'Jolteon Holo',
    set: 'Jungle',
    number: '4/64',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'base2-4',
  },
  {
    id: 'jungle-vaporeon',
    name: 'Vaporeon Holo',
    set: 'Jungle',
    number: '12/64',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'base2-12',
  },
  {
    id: 'jungle-flareon',
    name: 'Flareon Holo',
    set: 'Jungle',
    number: '3/64',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'base2-3',
  },

  // ─── VINTAGE — Fossil ──────────────────────────────────────────────────────
  {
    id: 'fossil-gengar',
    name: 'Gengar Holo',
    set: 'Fossil',
    number: '5/62',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'base3-5',
  },
  {
    id: 'fossil-moltres',
    name: 'Moltres Holo',
    set: 'Fossil',
    number: '12/62',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'base3-12',
  },
  {
    id: 'fossil-zapdos',
    name: 'Zapdos Holo',
    set: 'Fossil',
    number: '15/62',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'base3-15',
  },
  {
    id: 'fossil-articuno',
    name: 'Articuno Holo',
    set: 'Fossil',
    number: '2/62',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'base3-2',
  },

  // ─── VINTAGE — Gym ─────────────────────────────────────────────────────────
  {
    id: 'gym-blaines-charizard',
    name: "Blaine's Charizard Holo",
    set: 'Gym Challenge',
    number: '2/132',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'gym2-2',
  },

  // ─── VINTAGE — Neo Era ─────────────────────────────────────────────────────
  {
    id: 'neo-lugia',
    name: 'Lugia Holo',
    set: 'Neo Genesis',
    number: '9/111',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'neo1-9',
  },
  {
    id: 'neo-ho-oh',
    name: 'Ho-Oh Holo',
    set: 'Neo Revelation',
    number: '7/64',
    era: 'vintage',
    tier: 'vintage',
    tcgdexId: 'neo2-7',
  },
  {
    id: 'shining-gyarados',
    name: 'Shining Gyarados',
    set: 'Neo Revelation',
    number: '65/64',
    era: 'vintage',
    tier: 'iconic',
    tcgdexId: 'neo2-65',
  },
  {
    id: 'shining-magikarp',
    name: 'Shining Magikarp',
    set: 'Neo Revelation',
    number: '66/64',
    era: 'vintage',
    tier: 'iconic',
    tcgdexId: 'neo2-66',
  },

  // ─── ICONIC — E-Series ─────────────────────────────────────────────────────
  {
    id: 'crystal-charizard',
    name: 'Crystal Charizard',
    set: 'Skyridge',
    number: '146/144',
    era: 'vintage',
    tier: 'iconic',
    tcgdexId: 'ecard3-146',
  },
  {
    id: 'expedition-charizard',
    name: 'Charizard Holo',
    set: 'Expedition',
    number: '6/165',
    era: 'vintage',
    tier: 'iconic',
    tcgdexId: 'ecard1-6',
  },
  {
    id: 'skyridge-umbreon',
    name: 'Umbreon H30',
    set: 'Skyridge',
    number: 'H30/H32',
    era: 'vintage',
    tier: 'iconic',
    tcgdexId: 'ecard3-H30',
  },

  // ─── MODERN — Sword & Shield Alt Arts ──────────────────────────────────────
  {
    id: 'umbreon-vmax-alt',
    name: 'Umbreon VMAX Alt Art',
    set: 'Evolving Skies',
    number: '215/203',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'swsh7-215',
  },
  {
    id: 'rayquaza-vmax-alt',
    name: 'Rayquaza VMAX Alt Art',
    set: 'Evolving Skies',
    number: '218/203',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'swsh7-218',
  },
  {
    id: 'glaceon-vmax-alt',
    name: 'Glaceon VMAX Alt Art',
    set: 'Evolving Skies',
    number: '209/203',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'swsh7-209',
  },
  {
    id: 'leafeon-vmax-alt',
    name: 'Leafeon VMAX Alt Art',
    set: 'Evolving Skies',
    number: '205/203',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'swsh7-205',
  },
  {
    id: 'sylveon-vmax-alt',
    name: 'Sylveon VMAX Alt Art',
    set: 'Evolving Skies',
    number: '212/203',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'swsh7-212',
  },
  {
    id: 'mew-vmax-alt',
    name: 'Mew VMAX Alt Art',
    set: 'Fusion Strike',
    number: '269/264',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'swsh8-269',
  },
  {
    id: 'gengar-vmax-alt',
    name: 'Gengar VMAX Alt Art',
    set: 'Fusion Strike',
    number: '271/264',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'swsh8-271',
  },
  {
    id: 'giratina-vstar-alt',
    name: 'Giratina VSTAR Alt Art',
    set: 'Lost Origin',
    number: '131/196',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'swsh11-131',
  },
  {
    id: 'lugia-vstar-alt',
    name: 'Lugia VSTAR Alt Art',
    set: 'Silver Tempest',
    number: '202/195',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'swsh12-202',
  },
  {
    id: 'charizard-vstar-rainbow',
    name: 'Charizard VSTAR Rainbow',
    set: 'Brilliant Stars',
    number: '174/172',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'swsh9-174',
  },

  // ─── MODERN — Scarlet & Violet ─────────────────────────────────────────────
  {
    id: 'charizard-ex-obf',
    name: 'Charizard ex SAR',
    set: 'Obsidian Flames',
    number: '223/197',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'sv03-223',
  },
  {
    id: 'charizard-ex-151',
    name: 'Charizard ex SAR',
    set: 'Pokemon 151',
    number: '199/165',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'sv03.5-199',
  },
  {
    id: 'mew-ex-151',
    name: 'Mew ex SAR',
    set: 'Pokemon 151',
    number: '205/165',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'sv03.5-205',
  },
  {
    id: 'koraidon-ex-sar',
    name: 'Koraidon ex SAR',
    set: 'Scarlet & Violet',
    number: '254/198',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'sv01-254',
  },
  {
    id: 'miraidon-ex-sar',
    name: 'Miraidon ex SAR',
    set: 'Scarlet & Violet',
    number: '253/198',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'sv01-253',
  },
  {
    id: 'gardevoir-ex-sar',
    name: 'Gardevoir ex SAR',
    set: 'Scarlet & Violet',
    number: '245/198',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'sv01-245',
  },
  {
    id: 'iono-sar',
    name: 'Iono SAR',
    set: 'Paldea Evolved',
    number: '269/193',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'sv02-269',
  },
  {
    id: 'roaring-moon-ex-sar',
    name: 'Roaring Moon ex SAR',
    set: 'Paradox Rift',
    number: '251/182',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'sv04-251',
  },
  {
    id: 'iron-valiant-ex-sar',
    name: 'Iron Valiant ex SAR',
    set: 'Paradox Rift',
    number: '252/182',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'sv04-252',
  },
  {
    id: 'charizard-ex-paldean',
    name: 'Charizard ex SIR',
    set: 'Paldean Fates',
    number: '234/091',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'sv04.5-234',
  },

  // ─── MODERN — Full Art Trainers ────────────────────────────────────────────
  {
    id: 'marnie-fa',
    name: 'Marnie Full Art',
    set: 'Sword & Shield',
    number: '200/202',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'swsh1-200',
  },
  {
    id: 'cynthia-fa',
    name: 'Cynthia Full Art',
    set: 'Ultra Prism',
    number: '148/156',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'sm5-148',
  },
  {
    id: 'lillie-fa',
    name: 'Lillie Full Art',
    set: 'Ultra Prism',
    number: '151/156',
    era: 'modern',
    tier: 'modern-chase',
    tcgdexId: 'sm5-151',
  },
];

// ─── Index Configurations ──────────────────────────────────────────────────────
// Each index has its own card weights that sum to 1.0

export const INDEX_CONFIGS = {
  pmi: {
    name: 'PokeMarket Index',
    shortName: 'PMI',
    description: 'The benchmark — most valuable cards weighted by market significance',
    cards: [
      { id: 'base-charizard', weight: 0.12 },
      { id: 'crystal-charizard', weight: 0.10 },
      { id: 'umbreon-vmax-alt', weight: 0.10 },
      { id: 'base-blastoise', weight: 0.08 },
      { id: 'base-venusaur', weight: 0.08 },
      { id: 'rayquaza-vmax-alt', weight: 0.08 },
      { id: 'lugia-vstar-alt', weight: 0.07 },
      { id: 'charizard-ex-obf', weight: 0.07 },
      { id: 'giratina-vstar-alt', weight: 0.06 },
      { id: 'neo-lugia', weight: 0.06 },
      { id: 'charizard-ex-151', weight: 0.05 },
      { id: 'base-mewtwo', weight: 0.05 },
      { id: 'shining-gyarados', weight: 0.04 },
      { id: 'base-pikachu', weight: 0.04 },
    ],
    // Weights sum: 1.00
  },
  charizard: {
    name: 'Charizard Index',
    shortName: 'ZARD',
    description: 'Pure Charizard exposure — from Base Set to modern chase cards',
    cards: [
      { id: 'base-charizard', weight: 0.20 },
      { id: 'crystal-charizard', weight: 0.18 },
      { id: 'charizard-ex-obf', weight: 0.15 },
      { id: 'charizard-ex-151', weight: 0.12 },
      { id: 'gym-blaines-charizard', weight: 0.10 },
      { id: 'expedition-charizard', weight: 0.10 },
      { id: 'charizard-vstar-rainbow', weight: 0.08 },
      { id: 'charizard-ex-paldean', weight: 0.07 },
    ],
    // Weights sum: 1.00
  },
  vintage: {
    name: 'Vintage Index',
    shortName: 'VNTG',
    description: 'Nostalgia plays — Base Set through Neo era (1999-2002)',
    cards: [
      { id: 'base-charizard', weight: 0.18 },
      { id: 'crystal-charizard', weight: 0.12 },
      { id: 'neo-lugia', weight: 0.10 },
      { id: 'base-blastoise', weight: 0.10 },
      { id: 'base-venusaur', weight: 0.08 },
      { id: 'shining-gyarados', weight: 0.08 },
      { id: 'base-mewtwo', weight: 0.07 },
      { id: 'base-pikachu', weight: 0.06 },
      { id: 'fossil-gengar', weight: 0.05 },
      { id: 'neo-ho-oh', weight: 0.05 },
      { id: 'jungle-snorlax', weight: 0.04 },
      { id: 'skyridge-umbreon', weight: 0.04 },
      { id: 'base-raichu', weight: 0.03 },
    ],
    // Weights sum: 1.00
  },
  modern: {
    name: 'Modern Index',
    shortName: 'MDRN',
    description: 'Alt art momentum — Sword & Shield through Scarlet & Violet',
    cards: [
      { id: 'umbreon-vmax-alt', weight: 0.14 },
      { id: 'charizard-ex-obf', weight: 0.12 },
      { id: 'rayquaza-vmax-alt', weight: 0.10 },
      { id: 'giratina-vstar-alt', weight: 0.10 },
      { id: 'lugia-vstar-alt', weight: 0.09 },
      { id: 'charizard-ex-151', weight: 0.08 },
      { id: 'glaceon-vmax-alt', weight: 0.07 },
      { id: 'mew-vmax-alt', weight: 0.06 },
      { id: 'iono-sar', weight: 0.06 },
      { id: 'roaring-moon-ex-sar', weight: 0.05 },
      { id: 'koraidon-ex-sar', weight: 0.05 },
      { id: 'marnie-fa', weight: 0.04 },
      { id: 'charizard-ex-paldean', weight: 0.04 },
    ],
    // Weights sum: 1.00
  },
};

/** Look up a card by its id slug */
export function getCard(id) {
  return CARDS.find((c) => c.id === id) ?? null;
}

/** Cards grouped by tier */
export function getCardsByTier(tier) {
  return CARDS.filter((c) => c.tier === tier);
}
