/**
 * Card basket — single source of truth for all 100 tracked cards.
 * Weights live in INDEX_CONFIGS, not on individual cards.
 */
export const CARDS = [
  // ─── VINTAGE — Base Set ────────────────────────────────────────────────────
  {
    id: 'base-charizard',
    name: 'Charizard Holo',
    set: 'Base Set',
    number: '4/102',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Base Set Charizard Holo 4/102 PSA BGS CGC graded sold',
  },
  {
    id: 'base-blastoise',
    name: 'Blastoise Holo',
    set: 'Base Set',
    number: '2/102',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Base Set Blastoise Holo 2/102 sold',
  },
  {
    id: 'base-venusaur',
    name: 'Venusaur Holo',
    set: 'Base Set',
    number: '15/102',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Base Set Venusaur Holo 15/102 sold',
  },
  {
    id: 'base-pikachu',
    name: 'Pikachu',
    set: 'Base Set',
    number: '58/102',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Base Set Pikachu 58/102 yellow cheeks sold',
  },
  {
    id: 'base-mewtwo',
    name: 'Mewtwo Holo',
    set: 'Base Set',
    number: '10/102',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Base Set Mewtwo Holo 10/102 sold',
  },
  {
    id: 'base-raichu',
    name: 'Raichu Holo',
    set: 'Base Set',
    number: '14/102',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Base Set Raichu Holo 14/102 sold',
  },
  {
    id: 'base-gyarados',
    name: 'Gyarados Holo',
    set: 'Base Set',
    number: '6/102',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Base Set Gyarados Holo 6/102 sold',
  },
  {
    id: 'base-alakazam',
    name: 'Alakazam Holo',
    set: 'Base Set',
    number: '1/102',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Base Set Alakazam Holo 1/102 sold',
  },
  {
    id: 'base-chansey',
    name: 'Chansey Holo',
    set: 'Base Set',
    number: '3/102',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Base Set Chansey Holo 3/102 sold',
  },
  {
    id: 'base-ninetales',
    name: 'Ninetales Holo',
    set: 'Base Set',
    number: '12/102',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Base Set Ninetales Holo 12/102 sold',
  },
  {
    id: 'base-magneton',
    name: 'Magneton Holo',
    set: 'Base Set',
    number: '9/102',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Base Set Magneton Holo 9/102 sold',
  },
  {
    id: 'base-clefairy',
    name: 'Clefairy Holo',
    set: 'Base Set',
    number: '5/102',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Base Set Clefairy Holo 5/102 sold',
  },

  // ─── VINTAGE — Jungle ──────────────────────────────────────────────────────
  {
    id: 'jungle-scyther',
    name: 'Scyther Holo',
    set: 'Jungle',
    number: '10/64',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Jungle Scyther Holo 10/64 sold',
  },
  {
    id: 'jungle-snorlax',
    name: 'Snorlax Holo',
    set: 'Jungle',
    number: '11/64',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Jungle Snorlax Holo 11/64 sold',
  },
  {
    id: 'jungle-clefable',
    name: 'Clefable Holo',
    set: 'Jungle',
    number: '1/64',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Jungle Clefable Holo 1/64 sold',
  },
  {
    id: 'jungle-jolteon',
    name: 'Jolteon Holo',
    set: 'Jungle',
    number: '4/64',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Jungle Jolteon Holo 4/64 sold',
  },
  {
    id: 'jungle-vaporeon',
    name: 'Vaporeon Holo',
    set: 'Jungle',
    number: '12/64',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Jungle Vaporeon Holo 12/64 sold',
  },
  {
    id: 'jungle-flareon',
    name: 'Flareon Holo',
    set: 'Jungle',
    number: '19/64',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Jungle Flareon Holo 19/64 sold',
  },

  // ─── VINTAGE — Fossil ──────────────────────────────────────────────────────
  {
    id: 'fossil-gengar',
    name: 'Gengar Holo',
    set: 'Fossil',
    number: '5/62',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Fossil Gengar Holo 5/62 sold',
  },
  {
    id: 'fossil-lapras',
    name: 'Lapras Holo',
    set: 'Fossil',
    number: '10/62',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Fossil Lapras Holo 10/62 sold',
  },
  {
    id: 'fossil-moltres',
    name: 'Moltres Holo',
    set: 'Fossil',
    number: '12/62',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Fossil Moltres Holo 12/62 sold',
  },
  {
    id: 'fossil-zapdos',
    name: 'Zapdos Holo',
    set: 'Fossil',
    number: '15/62',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Fossil Zapdos Holo 15/62 sold',
  },
  {
    id: 'fossil-articuno',
    name: 'Articuno Holo',
    set: 'Fossil',
    number: '2/62',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Fossil Articuno Holo 2/62 sold',
  },

  // ─── VINTAGE — Gym Heroes / Challenge ──────────────────────────────────────
  {
    id: 'gym-blaines-charizard',
    name: "Blaine's Charizard Holo",
    set: 'Gym Challenge',
    number: '2/132',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: "Pokemon Blaine's Charizard Holo Gym Challenge 2/132 sold",
  },
  {
    id: 'gym-lt-surge-raichu',
    name: "Lt. Surge's Raichu Holo",
    set: 'Gym Heroes',
    number: '10/132',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: "Pokemon Lt Surge's Raichu Holo Gym Heroes 10/132 sold",
  },

  // ─── VINTAGE — Neo Genesis / Revelation / Destiny ──────────────────────────
  {
    id: 'neo-lugia',
    name: 'Lugia Holo',
    set: 'Neo Genesis',
    number: '9/111',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Lugia Holo Neo Genesis 9/111 sold',
  },
  {
    id: 'neo-ho-oh',
    name: 'Ho-Oh Holo',
    set: 'Neo Revelation',
    number: '16/64',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Ho-Oh Holo Neo Revelation 16/64 sold',
  },
  {
    id: 'neo-entei',
    name: 'Entei Holo',
    set: 'Neo Revelation',
    number: '6/64',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Entei Holo Neo Revelation 6/64 sold',
  },
  {
    id: 'neo-raikou',
    name: 'Raikou Holo',
    set: 'Neo Revelation',
    number: '24/64',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Raikou Holo Neo Revelation 24/64 sold',
  },
  {
    id: 'neo-suicune',
    name: 'Suicune Holo',
    set: 'Neo Revelation',
    number: '27/64',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Suicune Holo Neo Revelation 27/64 sold',
  },
  {
    id: 'shining-charizard',
    name: 'Shining Charizard',
    set: 'Neo Destiny',
    number: '107/105',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Shining Charizard Neo Destiny 107/105 sold',
  },
  {
    id: 'shining-gyarados',
    name: 'Shining Gyarados',
    set: 'Neo Destiny',
    number: '65/64',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Shining Gyarados Neo Destiny 65/64 sold',
  },
  {
    id: 'shining-magikarp',
    name: 'Shining Magikarp',
    set: 'Neo Destiny',
    number: '66/64',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Shining Magikarp Neo Destiny 66/64 sold',
  },
  {
    id: 'shining-raichu',
    name: 'Shining Raichu',
    set: 'Neo Destiny',
    number: '111/105',
    era: 'vintage',
    tier: 'vintage',
    ebayQuery: 'Pokemon Shining Raichu Neo Destiny 111/105 sold',
  },

  // ─── ICONIC — Crystal Types (Skyridge) ─────────────────────────────────────
  {
    id: 'crystal-charizard',
    name: 'Charizard Crystal',
    set: 'Skyridge',
    number: 'H3/H32',
    era: 'vintage',
    tier: 'iconic',
    ebayQuery: 'Pokemon Crystal Charizard Skyridge H3 sold',
  },
  {
    id: 'crystal-lugia',
    name: 'Lugia Crystal',
    set: 'Skyridge',
    number: 'H16/H32',
    era: 'vintage',
    tier: 'iconic',
    ebayQuery: 'Pokemon Crystal Lugia Skyridge H16 sold',
  },
  {
    id: 'crystal-nidoking',
    name: 'Nidoking Crystal',
    set: 'Skyridge',
    number: 'H14/H32',
    era: 'vintage',
    tier: 'iconic',
    ebayQuery: 'Pokemon Crystal Nidoking Skyridge H14 sold',
  },

  // ─── ICONIC — Gold Stars ───────────────────────────────────────────────────
  {
    id: 'gold-star-charizard',
    name: 'Charizard Gold Star',
    set: 'EX Team Rocket Returns',
    number: '100/109',
    era: 'vintage',
    tier: 'iconic',
    ebayQuery: 'Pokemon Charizard Gold Star EX Team Rocket Returns 100/109 sold',
  },
  {
    id: 'gold-star-rayquaza',
    name: 'Rayquaza Gold Star',
    set: 'EX Deoxys',
    number: '107/107',
    era: 'vintage',
    tier: 'iconic',
    ebayQuery: 'Pokemon Rayquaza Gold Star EX Deoxys 107/107 sold',
  },
  {
    id: 'umbreon-gold-star',
    name: 'Umbreon Gold Star',
    set: 'POP Series 5',
    number: '17/17',
    era: 'vintage',
    tier: 'iconic',
    ebayQuery: 'Pokemon Umbreon Gold Star POP Series 5 17/17 sold',
  },
  {
    id: 'espeon-gold-star',
    name: 'Espeon Gold Star',
    set: 'POP Series 5',
    number: '16/17',
    era: 'vintage',
    tier: 'iconic',
    ebayQuery: 'Pokemon Espeon Gold Star POP Series 5 16/17 sold',
  },
  {
    id: 'mew-gold-star',
    name: 'Mew Gold Star',
    set: 'EX Holon Phantoms',
    number: '101/110',
    era: 'vintage',
    tier: 'iconic',
    ebayQuery: 'Pokemon Mew Gold Star EX Holon Phantoms 101/110 sold',
  },
  {
    id: 'pikachu-gold-star',
    name: 'Pikachu Gold Star',
    set: 'EX Power Keepers',
    number: '104/108',
    era: 'vintage',
    tier: 'iconic',
    ebayQuery: 'Pokemon Pikachu Gold Star EX Power Keepers 104/108 sold',
  },
  {
    id: 'flareon-gold-star',
    name: 'Flareon Gold Star',
    set: 'POP Series 5',
    number: '10/17',
    era: 'vintage',
    tier: 'iconic',
    ebayQuery: 'Pokemon Flareon Gold Star POP Series 5 10/17 sold',
  },
  {
    id: 'vaporeon-gold-star',
    name: 'Vaporeon Gold Star',
    set: 'POP Series 5',
    number: '12/17',
    era: 'vintage',
    tier: 'iconic',
    ebayQuery: 'Pokemon Vaporeon Gold Star POP Series 5 12/17 sold',
  },
  {
    id: 'jolteon-gold-star',
    name: 'Jolteon Gold Star',
    set: 'POP Series 5',
    number: '11/17',
    era: 'vintage',
    tier: 'iconic',
    ebayQuery: 'Pokemon Jolteon Gold Star POP Series 5 11/17 sold',
  },

  // ─── ICONIC — Promo / Trophy ───────────────────────────────────────────────
  {
    id: 'pikachu-illustrator',
    name: 'Pikachu Illustrator',
    set: 'Promo',
    number: 'Promo',
    era: 'vintage',
    tier: 'iconic',
    ebayQuery: 'Pokemon Pikachu Illustrator promo card sold',
  },
  {
    id: 'no1-trainer',
    name: 'No. 1 Trainer',
    set: 'Japanese Promo',
    number: 'Promo',
    era: 'vintage',
    tier: 'iconic',
    ebayQuery: 'Pokemon No 1 Trainer Japanese promo trophy card sold',
  },
  {
    id: 'tropical-wind',
    name: 'Tropical Wind',
    set: 'Tropical Mega Battle Promo',
    number: 'Promo',
    era: 'vintage',
    tier: 'iconic',
    ebayQuery: 'Pokemon Tropical Wind promo Tropical Mega Battle sold',
  },
  {
    id: 'masters-key',
    name: "Master's Key",
    set: 'World Championship Promo',
    number: 'Promo',
    era: 'vintage',
    tier: 'iconic',
    ebayQuery: "Pokemon Master's Key World Championship promo 2010 sold",
  },

  // ─── ICONIC — EX Era key cards ─────────────────────────────────────────────
  {
    id: 'firered-charizard-ex',
    name: 'Charizard ex',
    set: 'EX FireRed & LeafGreen',
    number: '105/112',
    era: 'vintage',
    tier: 'iconic',
    ebayQuery: 'Pokemon Charizard ex EX FireRed LeafGreen 105/112 sold',
  },
  {
    id: 'delta-charizard',
    name: 'Charizard δ',
    set: 'EX Dragon Frontiers',
    number: '3/101',
    era: 'vintage',
    tier: 'iconic',
    ebayQuery: 'Pokemon Charizard delta EX Dragon Frontiers 3/101 sold',
  },
  {
    id: 'legend-lugia',
    name: 'Lugia LEGEND',
    set: 'HeartGold SoulSilver',
    number: '114/123',
    era: 'vintage',
    tier: 'iconic',
    ebayQuery: 'Pokemon Lugia LEGEND HeartGold SoulSilver 114/123 sold',
  },
  {
    id: 'legend-ho-oh',
    name: 'Ho-Oh LEGEND',
    set: 'HeartGold SoulSilver',
    number: '111/123',
    era: 'vintage',
    tier: 'iconic',
    ebayQuery: 'Pokemon Ho-Oh LEGEND HeartGold SoulSilver 111/123 sold',
  },

  // ─── MODERN CHASE — Sword & Shield Alt Arts ────────────────────────────────
  {
    id: 'umbreon-vmax-alt',
    name: 'Umbreon VMAX Alt Art',
    set: 'Evolving Skies',
    number: '215/203',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Umbreon VMAX Alt Art Evolving Skies 215/203 sold',
  },
  {
    id: 'rayquaza-vmax-alt',
    name: 'Rayquaza VMAX Alt Art',
    set: 'Evolving Skies',
    number: '218/203',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Rayquaza VMAX Alt Art Evolving Skies 218/203 sold',
  },
  {
    id: 'glaceon-vmax-alt',
    name: 'Glaceon VMAX Alt Art',
    set: 'Evolving Skies',
    number: '209/203',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Glaceon VMAX Alt Art Evolving Skies 209/203 sold',
  },
  {
    id: 'leafeon-vmax-alt',
    name: 'Leafeon VMAX Alt Art',
    set: 'Evolving Skies',
    number: '211/203',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Leafeon VMAX Alt Art Evolving Skies 211/203 sold',
  },
  {
    id: 'espeon-vmax-alt',
    name: 'Espeon VMAX Alt Art',
    set: 'Evolving Skies',
    number: '208/203',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Espeon VMAX Alt Art Evolving Skies 208/203 sold',
  },
  {
    id: 'sylveon-vmax-alt',
    name: 'Sylveon VMAX Alt Art',
    set: 'Evolving Skies',
    number: '212/203',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Sylveon VMAX Alt Art Evolving Skies 212/203 sold',
  },
  {
    id: 'calyrex-ice-vmax-alt',
    name: 'Ice Rider Calyrex VMAX Alt Art',
    set: 'Chilling Reign',
    number: '205/198',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Ice Rider Calyrex VMAX Alt Art Chilling Reign 205/198 sold',
  },
  {
    id: 'calyrex-shadow-vmax-alt',
    name: 'Shadow Rider Calyrex VMAX Alt Art',
    set: 'Chilling Reign',
    number: '214/198',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Shadow Rider Calyrex VMAX Alt Art Chilling Reign 214/198 sold',
  },
  {
    id: 'blaziken-vmax-alt',
    name: 'Blaziken VMAX Alt Art',
    set: 'Chilling Reign',
    number: '200/198',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Blaziken VMAX Alt Art Chilling Reign 200/198 sold',
  },
  {
    id: 'rapid-urshifu-vmax-alt',
    name: 'Rapid Strike Urshifu VMAX Alt Art',
    set: 'Battle Styles',
    number: '170/163',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Rapid Strike Urshifu VMAX Alt Art Battle Styles 170/163 sold',
  },
  {
    id: 'single-urshifu-vmax-alt',
    name: 'Single Strike Urshifu VMAX Alt Art',
    set: 'Battle Styles',
    number: '168/163',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Single Strike Urshifu VMAX Alt Art Battle Styles 168/163 sold',
  },
  {
    id: 'tyranitar-vmax-alt',
    name: 'Tyranitar VMAX Alt Art',
    set: 'Battle Styles',
    number: '166/163',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Tyranitar VMAX Alt Art Battle Styles 166/163 sold',
  },
  {
    id: 'mew-vmax-alt',
    name: 'Mew VMAX Alt Art',
    set: 'Fusion Strike',
    number: '269/264',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Mew VMAX Alt Art Fusion Strike 269/264 sold',
  },
  {
    id: 'gengar-vmax-alt',
    name: 'Gengar VMAX Alt Art',
    set: 'Fusion Strike',
    number: '271/264',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Gengar VMAX Alt Art Fusion Strike 271/264 sold',
  },
  {
    id: 'giratina-vstar-alt',
    name: 'Giratina VSTAR Alt Art',
    set: 'Lost Origin',
    number: '201/196',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Giratina VSTAR Alt Art Lost Origin 201/196 sold',
  },
  {
    id: 'aerodactyl-vstar-alt',
    name: 'Aerodactyl VSTAR Alt Art',
    set: 'Lost Origin',
    number: '203/196',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Aerodactyl VSTAR Alt Art Lost Origin 203/196 sold',
  },
  {
    id: 'lugia-vstar-alt',
    name: 'Lugia VSTAR Alt Art',
    set: 'Silver Tempest',
    number: '211/195',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Lugia VSTAR Alt Art Silver Tempest 211/195 sold',
  },
  {
    id: 'regieleki-vmax-alt',
    name: 'Regieleki VMAX Alt Art',
    set: 'Crown Zenith',
    number: '208/159',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Regieleki VMAX Alt Art Crown Zenith 208/159 sold',
  },
  {
    id: 'regidrago-vstar-alt',
    name: 'Regidrago VSTAR Alt Art',
    set: 'Crown Zenith',
    number: '209/159',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Regidrago VSTAR Alt Art Crown Zenith 209/159 sold',
  },

  // ─── MODERN CHASE — Scarlet & Violet era ──────────────────────────────────
  {
    id: 'obsidian-charizard-alt',
    name: 'Charizard ex Alt Art',
    set: 'Obsidian Flames',
    number: '228/197',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Charizard ex Alt Art Obsidian Flames 228/197 sold',
  },
  {
    id: 'charizard-ex-151',
    name: 'Charizard ex',
    set: 'Pokémon 151',
    number: '199/165',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Charizard ex 151 199/165 sold',
  },
  {
    id: 'mew-ex-151',
    name: 'Mew ex',
    set: 'Pokémon 151',
    number: '205/165',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Mew ex 151 205/165 sold',
  },
  {
    id: 'koraidon-ex-alt',
    name: 'Koraidon ex Alt Art',
    set: 'Scarlet & Violet',
    number: '254/198',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Koraidon ex Alt Art Scarlet Violet 254/198 sold',
  },
  {
    id: 'miraidon-ex-alt',
    name: 'Miraidon ex Alt Art',
    set: 'Scarlet & Violet',
    number: '255/198',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Miraidon ex Alt Art Scarlet Violet 255/198 sold',
  },
  {
    id: 'roaring-moon-ex-alt',
    name: 'Roaring Moon ex Alt Art',
    set: 'Paradox Rift',
    number: '245/182',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Roaring Moon ex Alt Art Paradox Rift 245/182 sold',
  },
  {
    id: 'iron-valiant-ex-alt',
    name: 'Iron Valiant ex Alt Art',
    set: 'Paradox Rift',
    number: '249/182',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Iron Valiant ex Alt Art Paradox Rift 249/182 sold',
  },
  {
    id: 'charizard-ex-paldean-fates',
    name: 'Charizard ex Shiny',
    set: 'Paldean Fates',
    number: 'SIR 191/091',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Charizard ex Shiny Paldean Fates 191/091 sold',
  },
  {
    id: 'bloodmoon-ursaluna-ex',
    name: 'Bloodmoon Ursaluna ex Alt Art',
    set: 'Twilight Masquerade',
    number: '228/167',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Bloodmoon Ursaluna ex Alt Art Twilight Masquerade 228/167 sold',
  },
  {
    id: 'ogerpon-cornerstone-ex',
    name: 'Ogerpon ex (Cornerstone) Alt Art',
    set: 'Twilight Masquerade',
    number: '220/167',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Ogerpon Cornerstone ex Alt Art Twilight Masquerade 220/167 sold',
  },
  {
    id: 'pecharunt-ex',
    name: 'Pecharunt ex Alt Art',
    set: 'Shrouded Fable',
    number: '103/064',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Pecharunt ex Alt Art Shrouded Fable 103/064 sold',
  },
  {
    id: 'terapagos-ex-alt',
    name: 'Terapagos ex Alt Art',
    set: 'Stellar Crown',
    number: '189/142',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Terapagos ex Alt Art Stellar Crown 189/142 sold',
  },
  {
    id: 'pikachu-ex-alt',
    name: 'Pikachu ex Alt Art',
    set: 'Surging Sparks',
    number: '245/191',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Pikachu ex Alt Art Surging Sparks 245/191 sold',
  },
  {
    id: 'raichu-ex-alt',
    name: 'Raichu ex Alt Art',
    set: 'Surging Sparks',
    number: '247/191',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Raichu ex Alt Art Surging Sparks 247/191 sold',
  },
  {
    id: 'dragapult-ex-alt',
    name: 'Dragapult ex Alt Art',
    set: 'Twilight Masquerade',
    number: '213/167',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Dragapult ex Alt Art Twilight Masquerade 213/167 sold',
  },
  {
    id: 'iron-thorns-ex-alt',
    name: 'Iron Thorns ex Alt Art',
    set: 'Paradox Rift',
    number: '248/182',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Iron Thorns ex Alt Art Paradox Rift 248/182 sold',
  },
  {
    id: 'garchomp-ex-alt',
    name: 'Garchomp ex Alt Art',
    set: 'Paradox Rift',
    number: '241/182',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Garchomp ex Alt Art Paradox Rift 241/182 sold',
  },
  {
    id: 'walking-wake-ex',
    name: 'Walking Wake ex Alt Art',
    set: 'Temporal Forces',
    number: '202/162',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Walking Wake ex Alt Art Temporal Forces 202/162 sold',
  },
  {
    id: 'iron-leaves-ex',
    name: 'Iron Leaves ex Alt Art',
    set: 'Temporal Forces',
    number: '203/162',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Iron Leaves ex Alt Art Temporal Forces 203/162 sold',
  },
  {
    id: 'munkidori-ex',
    name: 'Munkidori ex Alt Art',
    set: 'Shrouded Fable',
    number: '101/064',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Munkidori ex Alt Art Shrouded Fable 101/064 sold',
  },
  {
    id: 'eevee-ex-alt',
    name: 'Eevee ex Alt Art',
    set: 'Pokémon 151',
    number: '206/165',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Eevee ex Alt Art 151 206/165 sold',
  },
  {
    id: 'espathra-ex-alt',
    name: 'Espathra ex Alt Art',
    set: 'Paldea Evolved',
    number: '244/193',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Espathra ex Alt Art Paldea Evolved 244/193 sold',
  },
  {
    id: 'gardevoir-ex-alt',
    name: 'Gardevoir ex Alt Art',
    set: 'Scarlet & Violet',
    number: '245/198',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Gardevoir ex Alt Art Scarlet Violet 245/198 sold',
  },
  {
    id: 'arcanine-ex-alt',
    name: 'Arcanine ex Alt Art',
    set: 'Obsidian Flames',
    number: '222/197',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Arcanine ex Alt Art Obsidian Flames 222/197 sold',
  },
  {
    id: 'baxcalibur-ex-alt',
    name: 'Baxcalibur ex Alt Art',
    set: 'Paldea Evolved',
    number: '240/193',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Baxcalibur ex Alt Art Paldea Evolved 240/193 sold',
  },
  {
    id: 'flutter-mane-ex-alt',
    name: 'Flutter Mane ex Alt Art',
    set: 'Paradox Rift',
    number: '244/182',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Flutter Mane ex Alt Art Paradox Rift 244/182 sold',
  },
  {
    id: 'iron-hands-ex-alt',
    name: 'Iron Hands ex Alt Art',
    set: 'Paradox Rift',
    number: '246/182',
    era: 'modern',
    tier: 'modern-chase',
    ebayQuery: 'Pokemon Iron Hands ex Alt Art Paradox Rift 246/182 sold',
  },
];

// ─── Index Configurations ──────────────────────────────────────────────────────
// Each index has its own card weights that sum to 1.0

export const INDEX_CONFIGS = {
  pmi: {
    name: 'PokéMarket Index',
    shortName: 'PMI',
    description: 'Top 20 most significant cards across all eras — the benchmark index',
    cards: [
      { id: 'base-charizard', weight: 0.10 },
      { id: 'pikachu-illustrator', weight: 0.08 },
      { id: 'gold-star-charizard', weight: 0.08 },
      { id: 'shining-charizard', weight: 0.07 },
      { id: 'crystal-charizard', weight: 0.06 },
      { id: 'base-blastoise', weight: 0.06 },
      { id: 'umbreon-vmax-alt', weight: 0.06 },
      { id: 'obsidian-charizard-alt', weight: 0.05 },
      { id: 'base-venusaur', weight: 0.05 },
      { id: 'base-mewtwo', weight: 0.04 },
      { id: 'rayquaza-vmax-alt', weight: 0.04 },
      { id: 'umbreon-gold-star', weight: 0.04 },
      { id: 'giratina-vstar-alt', weight: 0.04 },
      { id: 'lugia-vstar-alt', weight: 0.04 },
      { id: 'charizard-ex-151', weight: 0.04 },
      { id: 'base-pikachu', weight: 0.04 },
      { id: 'mew-gold-star', weight: 0.03 },
      { id: 'gold-star-rayquaza', weight: 0.03 },
      { id: 'espeon-gold-star', weight: 0.03 },
      { id: 'neo-lugia', weight: 0.02 },
    ],
    // Weights sum: 1.00
  },
  charizard: {
    name: 'Charizard Index',
    shortName: 'ZARD',
    description: 'Every notable Charizard across all eras — tracks the Charizard premium',
    cards: [
      { id: 'base-charizard', weight: 0.20 },
      { id: 'shining-charizard', weight: 0.15 },
      { id: 'gold-star-charizard', weight: 0.15 },
      { id: 'crystal-charizard', weight: 0.12 },
      { id: 'obsidian-charizard-alt', weight: 0.10 },
      { id: 'charizard-ex-151', weight: 0.08 },
      { id: 'gym-blaines-charizard', weight: 0.06 },
      { id: 'firered-charizard-ex', weight: 0.06 },
      { id: 'delta-charizard', weight: 0.04 },
      { id: 'charizard-ex-paldean-fates', weight: 0.04 },
    ],
    // Weights sum: 1.00
  },
  vintage: {
    name: 'Vintage Index',
    shortName: 'VNTG',
    description: 'Base Set through Neo era — the original Pokémon TCG market',
    cards: [
      { id: 'base-charizard', weight: 0.18 },
      { id: 'shining-charizard', weight: 0.12 },
      { id: 'neo-lugia', weight: 0.10 },
      { id: 'base-blastoise', weight: 0.08 },
      { id: 'base-venusaur', weight: 0.07 },
      { id: 'base-pikachu', weight: 0.06 },
      { id: 'base-mewtwo', weight: 0.06 },
      { id: 'shining-gyarados', weight: 0.05 },
      { id: 'neo-ho-oh', weight: 0.05 },
      { id: 'fossil-gengar', weight: 0.04 },
      { id: 'jungle-scyther', weight: 0.04 },
      { id: 'jungle-snorlax', weight: 0.04 },
      { id: 'base-raichu', weight: 0.04 },
      { id: 'neo-entei', weight: 0.03 },
      { id: 'neo-suicune', weight: 0.03 },
      { id: 'shining-raichu', weight: 0.01 },
    ],
    // Weights sum: 1.00
  },
  modern: {
    name: 'Modern Index',
    shortName: 'MDRN',
    description: 'Sword & Shield through current era — the premium alt art market',
    cards: [
      { id: 'umbreon-vmax-alt', weight: 0.15 },
      { id: 'obsidian-charizard-alt', weight: 0.12 },
      { id: 'rayquaza-vmax-alt', weight: 0.10 },
      { id: 'giratina-vstar-alt', weight: 0.10 },
      { id: 'lugia-vstar-alt', weight: 0.09 },
      { id: 'charizard-ex-151', weight: 0.08 },
      { id: 'glaceon-vmax-alt', weight: 0.06 },
      { id: 'leafeon-vmax-alt', weight: 0.06 },
      { id: 'mew-vmax-alt', weight: 0.05 },
      { id: 'roaring-moon-ex-alt', weight: 0.05 },
      { id: 'iron-valiant-ex-alt', weight: 0.05 },
      { id: 'bloodmoon-ursaluna-ex', weight: 0.05 },
      { id: 'pikachu-ex-alt', weight: 0.04 },
    ],
    // Weights sum: 1.00
  },
};

/** Look up a card by its id slug */
export function getCard(id) {
  return CARDS.find((c) => c.id === id) ?? null;
}

/** Cards grouped by tier */
export function getCardsByTier(tier) {
  return CARDS.filter((c) => c.tier === tier);
}
